name: Sync Upstream

on:
  schedule:
    # 每天凌晨2点同步（UTC时间）
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync upstream repository
        run: |
          # 添加原始仓库为上游
          git remote add upstream https://github.com/sjzar/chatlog.git
          # 获取上游仓库更新
          git fetch upstream
          # 合并上游仓库的main分支到当前分支（根据实际分支名修改）
          git checkout main
          git merge upstream/main
          # 推送更新到当前fork仓库
          git push origin main
